version: '3.4'

services:
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
     - "5000:5000"
    depends_on:
          - db
    container_name: webapplication1
      
  db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Atlo2DrP1"
            ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"

        container_name: db
